name: Bale Bot - JSON Server Test

on:
  workflow_dispatch:   # اجرای دستی

jobs:
  run-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 180   # ۳ ساعت

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install requests
        run: pip install requests

      - name: Run bot
        env:
          BALE_BOT_TOKEN: ${{ secrets.BALE_BOT_TOKEN }}
        run: python Bot.py
